### ISSUE TITLE
Mathematica support/testing

### ISSUE THREAD

**Issue by arnoudbuzing** [LaurentRDC/pandoc-plot#1]
Laurent, 

I work for Wolfram Research and noticed your comment on this page: https://github.com/LaurentRDC/pandoc-plot/releases : "or if you would like to help test Mathematica support". Let me know if you need any (additional) licenses for Mathematica or Wolfram Engine, or if you're interesting in joining our developer/prerelease program.

Thanks,
Arnoud

**Comment by LaurentRDC** [comment]
Hello Arnoud,

I have a Mathematica license through my university (McGill University). Currently trying to install it on my workstation. 

I would be interested in the developer program, especially if it helps with testing. Is there a web page that describes this program? The only thing I can find is [Wolfram for Software Devs](https://www.wolfram.com/developer/).

**Comment by arnoudbuzing** [comment]
Yes, please email prerelease@wolfram.com and mention me (Arnoud Buzing) and we will add you. Additionally we now have Wolfram Engine (https://www.wolfram.com/engine/), which is a program to support projects like yours.

**Comment by LaurentRDC** [comment]
I got access, thank you!
