### ISSUE TITLE
Feature Request: Caching dependent on external files

### ISSUE THREAD

**Issue by syntonym** [LaurentRDC/pandoc-plot#10]
To speed up calculations pandoc-plot caches figures, identified by the hash of the source code. If the figure code depends on external code or data, these external dependencies can change, but pandoc-plot will not regenerate the figure.

Example report:

    ```{.bokeh format=HTML}
    import json
    from bokeh.plotting import figure 
    with open("data.json", mode="rb") as f:
        data = json.load(f)

    p = figure(width=300, height=300)
    p.line(x=data["x"], y=data["y"])
    ```

I suggest adding an attribute `depends` that designates files that the figure depends on. If any of these files changes, the figure should be regenerated. Example:

    ```{.bokeh format=HTML depends=data.json}

In #8 LaurentRDC mentioned alternatively a `cache` parameter, that would disable caching for one figure:

    ```{.bokeh format=HTML cache=False}

In this case if caching is critical, it could be implemented in the figure generating code by the user.

**Comment by LaurentRDC** [comment]
Actually, I think I prefer your `depends` suggestion. I'm going to look around for a good cross-platform file hashing solution, e.g. `Get-FileHash` on Windows.

**Comment by LaurentRDC** [comment]
I have opted to allow for a _list_ of dependencies instead of a single one (that's something I personally would use), and so here's the syntax that I have implemented:

````markdown
```{.python .bokeh dependencies=[data1.json, data2.json]}
# plotting ...
```
````

**Comment by LaurentRDC** [comment]
The change is live in the latest version ([0.9.0.0](https://github.com/LaurentRDC/pandoc-plot/releases/tag/0.9.0.0)).

Thanks for the suggestion! Try it out and don't hesitate to re-open this issue if there's a problem.

**Comment by syntonym** [comment]
I have tested the dependencies and the svg output and both work great, thank you!
