### ISSUE TITLE
Same Problem as Issue2

### ISSUE THREAD

**Issue by MiuKaShi** [LaurentRDC/pandoc-plot#12]
Hi,
I update to the latest pandoc-plot, but get an error when plotting.

```
ERROR | ended with exit code ExitFailure 1
ERROR | *******
ERROR | 'C:\Program' is not recognized as an internal or external command,
ERROR | operable program or batch file.
ERROR |
ERROR | *******
ERROR | Running command
```
The gnuplot was installed in my C:\ Program Files\ xxxxx. it seems the space between Program and Files cause the error. This Problem may be the same as  [issue#2
](https://github.com/LaurentRDC/pandoc-plot/issues/2). 

Please fix it, thank you

**Comment by LaurentRDC** [comment]
I'll close this for now. Don't hesitate to re-open the issue if the problem persists.
