### ISSUE TITLE
Data frames as Table

### ISSUE THREAD

**Issue by chain-ed-reaction** [LaurentRDC/pandoc-plot#14]
I believe having an option to output data frames say from pandas or R datagrams, as table could be a future feature addition.

**Comment by LaurentRDC** [comment]
Hi Bevan,

That's a good idea for a filter. The machinery is similar to `pandoc-plot` , in the sense that you would need to capture the output of a program. However, it is out-of-scope for `pandoc-plot`, which is oriented towards making figures.

If you need this for yourself, you can learn more on how to make Pandoc filters here: [https://pandoc.org/filters](https://pandoc.org/filters)
