### ISSUE TITLE
using unicode Greek letters causes an error in plotsjl

### ISSUE THREAD

**Issue by YutaroIshihama** [LaurentRDC/pandoc-plot#16]
Julia language accepts unicodes such as Greek letters, subscripted digits. But, using these characters causes an error while running the pandoc. By avoiding this with ` e10(x)=real(beta0(x)+nu0(x))`, it will be OK. I would prefer using ε, β, ν instead. Is this a specification of this filter?

**Comment by LaurentRDC** [comment]
Hello,

That's unfortunate. I will fix it as soon as I can. Some questions:
* What error are you getting? Can you copy-paste the error?
* What version of pandoc / pandoc-plot are you using?
* Can you write down a simple exampel that reproduces the error, so I can test it here?

**Comment by LaurentRDC** [comment]
I think I have found the problem. Haskell is a bit particular about setting explicitly the default encoding of the environment. 

For example, the following example works **after** the fix:

````markdown
# Verifying that unicode symbols work with the PlotJL toolkit

```{.plotsjl}
using Plots
plot(sin, (x->begin
            sin(2x)
        end), 0, 2π, line = 4, leg = false, fill = (0, :orange))
```
````

I've also added a test that prevent this error from happening again. If the tests pass, I will release version 1.0.2.0 today.

**Comment by LaurentRDC** [comment]
[Version 1.0.1.0 is live](https://github.com/LaurentRDC/pandoc-plot/releases/tag/1.0.1.0), which fixes this issue.

If there is still a problem, do not hesitate to re-open this issue.

**Comment by YutaroIshihama** [comment]
Dear Dr. Laurent P Rene de Cotret,

Thanks very much for your prompt efforts. I will check it later.
Also, I posted several comments helpful to another open issue.

Sincerely

T. Makino
