### ISSUE TITLE
Plotly module

### ISSUE THREAD

**Issue by xubeisi** [LaurentRDC/pandoc-plot#17]
hi, Thanks for develop this nice filter, somehow the matplotlib module works but plotly module doesn't. 
Could you help me findout why? Thank you!

I am in Conda environment, and versions are
```text
#conda install -y -c plotly plotly-orca psutil requests
#conda install -y pandoc=2.11.3.2 pandoc-plot
pandoc                    2.11.3.2             h7f98852_0    conda-forge
pandoc-plot               1.0.2.1              ha770c72_0    conda-forge
pandocfilters             1.4.3            py38h06a4308_1    defaults
plotly                    4.14.3             pyhd3eb1b0_0    defaults
plotly-orca               1.3.1                         1    plotly
python                    3.8.5                h7579374_1    defaults
```
Error
```
pandoc --filter pandoc-plot input.md --output output.html --verbose
[INFO] Running filter pandoc-plot
[pandoc-plot] ERROR | Running command
[pandoc-plot] ERROR |     python3 -c "import plotly.graph_objects"
[pandoc-plot] ERROR | ended with exit code ExitFailure 1
[pandoc-plot] ERROR | *******
[pandoc-plot] ERROR | Traceback (most recent call last):
[pandoc-plot] ERROR |   File "<string>", line 1, in <module>
[pandoc-plot] ERROR | ModuleNotFoundError: No module named 'plotly'
[pandoc-plot] ERROR |
[pandoc-plot] ERROR | *******
[pandoc-plot] WARN  | Renderer for Python/Plotly needed but is not installed
[INFO] Completed filter pandoc-plot in 59 ms
```

import in command line seems works. 
```bash
python -c "import matplotlib" && echo $?
0
python -c "import plotly.graph_objects" && echo $?
0
```

minimal file input.md

~~~text
# My document

This is a paragraph.

```{.matplotlib}
import matplotlib.pyplot as plt

plt.figure()
plt.plot([0,1,2,3,4], [1,2,3,4,5])
plt.title('This is an example figure')
```
```{.plotly_python caption="This is a caption"}
import plotly.graph_objects as go
fig = go.Figure(data=go.Bar(y=[2, 3, 1]))
```
~~~

**Comment by LaurentRDC** [comment]
Hi!

The only thing I can think of is that `pandoc-plot` defaults to using `python3`. From this line:

```bash
[pandoc-plot] ERROR |     python3 -c "import plotly.graph_objects"
```

I'm not a user of Linux/MacOS, but does python3 refer to your conda installation, or your system installation?

**Comment by xubeisi** [comment]
thanks for quick reply! it should be my conda installation, I also tried manually provide python location in config file. None worked. 

But I think you are point to a good direction. However, I am not familiar with Haskell. 

Would you mind help me find a way to print python output in 

https://github.com/LaurentRDC/pandoc-plot/blob/master/src/Text/Pandoc/Filter/Plot/Renderers/PlotlyPython.hs ? 

so I could 
```
import sys
print(sys.executable)
```

to find out which one it use. 

Thank you!

**Comment by LaurentRDC** [comment]
Hmm pandoc-plot does not capture stdout, so printing like you suggested wouldn't work. What you can do instead is write to file:

Here's `input.md`:

````markdown
# My document

This is a paragraph.

```{.matplotlib}
import matplotlib.pyplot as plt
import sys

print(sys.executable, file="here.txt")

plt.figure()
plt.plot([0,1,2,3,4], [1,2,3,4,5])
plt.title('This is an example figure')
```
````

then the content of file `"here.txt"` will help us diagnose the problem

**Comment by xubeisi** [comment]
works and you first thought were right, it was using the system python but not the conda one..

In my .pandoc-plot.yml I tried change the python path
```
# The possible parameters for the Matplotlib toolkit
matplotlib:
  # preamble: matplotlib.py
  tight_bbox: false
  transparent: false
  executable: /home/user/.conda/python
  command_line_arguments:
```
I also tried
```
-M plot-configuration=/path/to/file.yml
```

or put in input.md 

```
---
title: My document
author: John Doe
plot-configuration: /home/user/pandoc-plot/.pandoc-plot.yml
---
```

still using system python, it report error and here.txt won't be generated. 
```
[INFO] Running filter pandoc-plot
[pandoc-plot] ERROR | Dependency file1.txt does not exist.
[pandoc-plot] ERROR | Dependency file2.txt does not exist.
[INFO] Completed filter pandoc-plot in 9 ms
```

I looked around pandoc's document, maybe they just didn't support virtual env? 

Thank you!

**Comment by LaurentRDC** [comment]
Allright let me know if you have any other issue!
