### ISSUE TITLE
Feature Request: Support for planuml toolkit

### ISSUE THREAD

**Issue by fusedFET** [LaurentRDC/pandoc-plot#18]
Hello, 
I just found this extension and I love it :)

Would you be interested in adding the [Plantuml](https://plantuml.com/en/) toolkit?

It might be a bit trickyer than other toolkits because it needs to be runned using java, but I think it would be a great addition !

I use it to document firmware projects but also cloud architectures and more.
There are tons of examples on their website and it is also open-source.

**Comment by LaurentRDC** [comment]
Hi, @fusedFET,

I'm glad pandoc-plot is useful to you. It should be easy to add plantuml! I'll play around with it today. The dependence on Java shouldn't be a problem.

**Comment by LaurentRDC** [comment]
@fusedFET Look out for version 1.1.0 (to be released soon) which will support PlantUML
