### ISSUE TITLE
How to run this filter directly from YAML.

### ISSUE THREAD

**Issue by VolkovIlia** [LaurentRDC/pandoc-plot#20]
I have installed pandoc-plot from AUR. How to exec this filter from YAML. It works great when I use --filter=pandoc-plot, but when I use YAML:
```
filters:
 - pandoc-plot
 ```
It does not work. What is the right way to call it from YAML?

**Comment by LaurentRDC** [comment]
Hello,

I am not sure. In the documentation for pandoc, the defaults file looks like so:

```yaml
filters:
- wordcount.lua
```

Note that there is no space between before "-". Maybe that's the problem? Try this:

```yaml
filters:
- pandoc-plot
```

**Comment by VolkovIlia** [comment]
No( It does not work((

**Comment by LaurentRDC** [comment]
Hmm would you be able to share a small example document, as well as the command you are using?

Laurent


________________________________

**Comment by VolkovIlia** [comment]
```markdown
---
bibliography: lib.bib
title: Test
author: Name
filters:
- pandoc-plot
plot-configuration: config.yaml
---

# Bla bla

BBla [@AB_patent_Pomerantz_1968]

```{.matplotlib}
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(23)

# Compute areas and colors
N = 150
r = 2 * np.random.rand(N)
theta = 2 * np.pi * np.random.rand(N)
area = 200 * r**2
colors = theta

fig = plt.figure()
ax = fig.add_subplot(111, projection='polar')
c = ax.scatter(theta, r, c=colors, s=area, cmap='hsv', alpha=0.75)
```
```
pandoc test_groff.md -t ms -C -o test_groff.pdf
```
for pandoc-plot
```yaml
format: EPS
````

**Comment by LaurentRDC** [comment]
You are right, it does not work on my machine either.

However, I've tried with other filters (e.g. pandoc-crossref) and I get the same result: pandoc does not recognize the `filters` field, it seems.

**Comment by LaurentRDC** [comment]
You want might to raise an issue in https://github.com/jgm/pandoc

**Comment by LaurentRDC** [comment]
Also, to get EPS output you need the following `config.yaml`:

```yaml
matplotlib:
  format: EPS
```

**Comment by LaurentRDC** [comment]
Well seems like this is not a supported way to use filter. Don't hesitate to open other issues if other problems arise!
