### ISSUE TITLE
Inline SVG

### ISSUE THREAD

**Issue by agbell** [LaurentRDC/pandoc-plot#23]
Great project. I am using pandoc to generate HTML from markdown for a Jekyll site and trying to use pandoc-plot with it.

It would be great if there was an option to inline  SVG images into the HTML (or other formats that support it).

**Comment by LaurentRDC** [comment]
Ahh yes I see. 

That's what pandoc-plot is already doing for HTML "plots" in HTML documents, like the interactive [bokeh example on the website](https://laurentrdc.github.io/pandoc-plot).

I can add a special case that embeds SVG plots from any toolkit in HTML output.

**Comment by LaurentRDC** [comment]
I would have to break backwards compatibility to make pandoc-plot aware of the target format, unfortunately.

However, you can use the following python filter to embed SVG from files:

```python
# embed-svg.py
from pandocfilters import toJSONFilter, Image, RawInline

def embed_svg(key, value, format, meta):
  if key == 'Image':
    attrs, caption, (url, title) = value
    if url.endswith('.svg'):
        svg_content = open(url, mode='r').read()
        return RawInline("html5", f"<svg>\n{svg_content}\n</svg>\n") # requires python 3.6 for f-strings

if __name__ == "__main__":
  toJSONFilter(embed_svg)
```

This example is made simpler by discarding the caption. Then you can use it as:

```sh
pandoc --filter pandoc-plot --filter embed-svg.py -i test.md -t ...
```

Note the order of filters!

**Comment by agbell** [comment]
I will try this, thanks! I didn't expect you to write scripts for me, but I appreciate it :)

**Comment by agbell** [comment]
This worked, thanks

**Comment by LaurentRDC** [comment]
Great, so I will close this for now. 

In the future, when I think it's OK to break backwards compatibility, I'll add the option to do this from within pandoc-plot.
