### ISSUE TITLE
Allow specifying language on code blocks for tools like VSCode

### ISSUE THREAD

**Issue by lmarianski** [LaurentRDC/pandoc-plot#25]
Currently, at least as far as i know for the codeblocks to be picked up by pandoc-plot they have to exactly match the format specified in the readme, which disables syntax highlighting and language features in editors like VSCode. I'td be nice if you could use something liike this:

\```py{.matplotlib}
import matplotlib.pyplot as plt
\```

for the marker, it looks like this is still recognized by vscode as a python code block, so you just need to allow this in pandoc-plot

**Comment by LaurentRDC** [comment]
Hi there!

The README example is short but incomplete. The [documentation](https://laurentrdc.github.io/pandoc-plot/MANUAL.html#parameters-and-options) explains that syntax highlighting can be activated like so:

````markdown

```{.python .matplotlib caption="example"}
import matplotlib.pyplot as plt
plt.plot([1,2,3,4])
```

````

I personally use VScode without any Markdown-specific extensions and syntax highlighting works correctly using the above snippet.

**Comment by lmarianski** [comment]
Ah, thx, didn't know about that
