### ISSUE TITLE
How to force position of plot like latex "figure"

### ISSUE THREAD

**Issue by VolkovIlia** [LaurentRDC/pandoc-plot#29]
In latex I can specify position of figure by:
```
   \begin{figure}[htpb]
    ... figure contents...
    \end{figure}
```
How to do that in pandoc-plot?

**Comment by LaurentRDC** [comment]
Hi Ilia,

I'm not sure how to do this. `pandoc-plot` converts a code block to a figure block. In the conversion, some information is lost by `pandoc`. The precise information which is kept depends on the source format.

Are you converting from latex or to latex?

**Comment by LaurentRDC** [comment]
I don't this this question is directly related to pandoc-plot. I'll close this for now but **don't hesitate to re-open** if you need more help.

**Comment by VolkovIlia** [comment]
Sorry for waiting.

I use pandoc with pandoc-plot for writing articles. My workflow is markdown --> pdf + docx. But when I trying to add some plot (matplotlib) it appears somewhere in text after but not in direct place where I want. So, my question is how determine place for the plot? 
Command that I use:

```
pandoc -F pandoc-plot -F pandoc-crossref  -F pandoc-chem-struct --highlight-style=kate -s -C -o  "$base".pdf "$file" | pandoc -F pandoc-plot -F pandoc-crossref   -F pandoc-chem-struct --highlight-style=kate -s -C -o  "$base".docx "$file" ;;
```

Structure that I use:
```
{.python .matplotlib caption="XRD" preamble=include.py #fig:XRD}
```

**Comment by LaurentRDC** [comment]
No worries.

There's no way to control figure placement with `pandoc-plot`. Figure placement is based on which input format `pandoc` understands. For example, if your source document is in Markdown, then there's no way to set figure placement. See for example https://github.com/jgm/pandoc/issues/845.

I hope this helps. Keep an eye on https://github.com/jgm/pandoc/issues/3177. What you're looking for will be implemented in the near future.

**Comment by VolkovIlia** [comment]
Thanks! It working for me!)
