### ISSUE TITLE
plantuml filename incorrect

### ISSUE THREAD

**Issue by iainwp** [LaurentRDC/pandoc-plot#30]
with the attached markdown [a.md](https://github.com/LaurentRDC/pandoc-plot/files/6991318/a.md)

the `plantuml.txt` file generated to run `plantuml` on has a different stem filename to the one put into the `html` file.  `plantuml` therefore generates a `png` or `pdf` file with the wrong filename.

**Comment by LaurentRDC** [comment]
Hello,

pandoc-plot generates filenames itself, which is part of its caching system. Are you saying that this is incorrect? Can you include the input code, the command you use, and the output that is generated?

For example, on my personal website: 

````markdown
```{.python .matplotlib directory="generated" format=PNG caption="Diffraction pattern of graphite"}
...
```
````

becomes this:

```html
<figure>
<img src="generated\17792115765669059365.png" 
     class="python image" 
     alt="Diffraction pattern of graphite (Source code)" />
<figcaption aria-hidden="true">Diffraction pattern of graphite (<a href="generated\17792115765669059365.src.html">Source code</a>)</figcaption>
</figure>
```

using `pandoc --filter pandoc-plot -i post.md -t html`

**Comment by iainwp** [comment]
the filename of the file that plantuml generates is incorrect.  i think this is because it generates it from the .txt file you feed to plantuml.

i run `pandoc a.md -F pandoc-plot` on the `a.md` file attached to my first post.

thanks.

iain

**Comment by LaurentRDC** [comment]
Iain,

I don't have enough information to determine if you're talking about a bug or if the documentation on how to use pandoc-plot is lacking. 

Can you provide the output HTML? If you used a configuration file, please also provide it. Thanks!

**Comment by iainwp** [comment]
I would say it's a bug in your interaction with `plantuml`.  With the `a.md` from my first post:
```
➜  tmp pandoc -w html a.md -F pandoc-plot
<h1 id="heading">heading</h1>
<h2 id="subheading">subheading</h2>
<p>this is text</p>
<figure>
<img src="`plots/14700905079715265809.png`" alt="test" /><figcaption aria-hidden="true">test</figcaption>
</figure>
```
This generates the following file (shortened path) `/var/folders/t2/.../T/pandocplot3719405408627858950.txt`
which I assume you then invoke `pandoc` on which generates `plots/pandocplot3719405408627858950.png` .  However, the HTML is referencing `plots/14700905079715265809.png`.  There is a mismatch in these filenames.  This is a problem with `plantuml` includes but not `matplotlib` (I've not tried any others).  I'm using `pandoc-plot` v1.2.3 from homebrew on a mac.

Thanks for listening.  I'll be using this a lot.

**Comment by LaurentRDC** [comment]
Ok I'm able to reproduce the problem now. Thank you for your patience. I'm testing a fix.

If tests pass, I will try to release a new version in the next 24h.

**Comment by LaurentRDC** [comment]
All right version 1.3.0 fixes this problem, at least with the most recent version of PlantUML. I've added an extra end-to-end test to make sure this problem never happens again. 

Please try it at your earliest convenience and let me know if it works for you!

**Comment by iainwp** [comment]
That works on my simple test cases.
Many thanks.
