### ISSUE TITLE
Publisher in version 1.3.0 got messed up

### ISSUE THREAD

**Issue by OfficialEsco** [LaurentRDC/pandoc-plot#31]
![image](https://user-images.githubusercontent.com/15158490/130111133-2d3792a0-c830-4519-bf07-58f54a1a93bb.png)

https://github.com/microsoft/winget-pkgs/pull/25465

**Comment by LaurentRDC** [comment]
Hello,

What am I looking at? I don't maintain distributions of pandoc-plot except conda-forge.

**Comment by OfficialEsco** [comment]
You are looking at a Screenshot of Windows Add or Remove Programs, aka the Registry Strings metadata.
Your `é` got converted to `Ã©` in some way or another.

You've added pandoc-plot to WinGet in the past and since you're not uploading it we Package Maintainers pick it up on our RSS feeds/Automation.

This is not a problem on our end, just wanted to let you the developer known there is a issue with your Metadata.

**Comment by LaurentRDC** [comment]
I think my name always shows up like this. This might be an issue with the software I use to package pandoc-plot into an installer (Inno setup), but I don't have the energy to overhaul this.

Thanks for notifying me!
