### ISSUE TITLE
yaml-0.11.7.0 has a change which breaks newest version (1.3.0) on Hackage

### ISSUE THREAD

**Issue by bcw** [LaurentRDC/pandoc-plot#32]
Using pandoc-plot-1.3.0, in the [newest version (0.11.7.0) of yaml](https://hackage.haskell.org/package/yaml-0.11.7.0) on Hackage, [`(.:?)`](https://hackage.haskell.org/package/yaml-0.11.7.0/docs/Data-Yaml.html#v:.:-63-) now takes an `Aeson.Key.Key` instead of `Text` as second argument. This caused building a Hakyll site to fail for me; I am new to both Hakyll and your package, so there might be some other workaround I don't know of, but I had to add a dependency like `yaml == 0.11.6.*` to get it to compile.

It took me several hours to figure out what the problem was (at first I thought I needed a GHC pragma), so I hope it can be fixed to avoid that headache for others.  Since you're using `yaml >= 0.8 && < 1` right now, I think changing it to `yaml >= 0.8 && < 0.11.7` should make your package keep working until someone finds a way to support the new way (like using some class `Key` and `Text` are both in, or something).

Anyway, thank you for your work on this project.  Until I thought to search for something like this, I was building a simple site using a separate image compilation step with a `Makefile` and LaTeX, but I think this way will be much more convenient.

**Comment by LaurentRDC** [comment]
Thank you for your report. I have updated the Hackage bounds to prevent this problem with version 1.3.0 of `pandoc-plot`.

I'm adding support for `aeson` 2.x right now for version 1.4.0, which should make `pandoc-plot` work with `yaml` 0.11.7+

**Comment by bcw** [comment]
Wow, that was fast. :smile: I guess this issue can be closed now.

**Comment by LaurentRDC** [comment]
`pandoc-plot` version 1.4.0 was just released on Hackage. It will work with `aeson` 2+ (and ONLY `aeson` v2+, for ease of maintenance).

The executables should be published on GitHub today.
