### ISSUE TITLE
Pandoc plot does not recognize the Matplotlib I installed

### ISSUE THREAD

**Issue by fanrongqitiancai** [LaurentRDC/pandoc-plot#34]
My running environment is Windows 7

1. Run the python command and the result is

python 3.8.5

2. Run the PIP list command to display

matplotlib 3.5.1

3. Run the pandoc plot toolkits command to display:

Toolkit: python/matplotlib

code block trigger: matplotlib

4. Markdown file

```{.matplotlib}

import matplotlib. pyplot as plt



plt. figure()

plt. plot([0,1,2,3,4], [1,2,3,4,5])

plt. title('This is an example figure')

```

5. Operation

pandoc --filter pandoc-plot --highlight-style pygments markdown. md -s -o output. html

6. Error reporting

renderer for python/matplotlib needed but is not installed

**Comment by LaurentRDC** [comment]
Hello there,

I'm sorry you're having trouble. I notice that your markdown file doesn't look like what `pandoc-plot` expects. Can you try the following file?

````markdown
# My document

```{.matplotlib}
import matplotlib.pyplot as plt

plt.figure()
plt.plot([0,1,2,3,4], [1,2,3,4,5])
plt.title('This is an example figure')
```

````

It is important that your plotting code be 'sandwiched' between ` ```{.matplotlib} ` and ` ``` `

**Comment by fanrongqitiancai** [comment]
My document is in ```  。I think there is a problem with pandoc plot or Python environment variables, which leads to incorrect identification. My pandoc plot downloads exe files and communicates with Pando Exe is in the same directory.

**Comment by LaurentRDC** [comment]
Allright, let's turn on logging to see what's going on.

In the same repository as your file, can you create a file named `.pandoc-plot.yml` with the following content?

```yaml
# .pandoc-plot.yml
logging:
    verbosity: debug
```

Then, if you run the conversion command `pandoc --filter pandoc-plot markdown.md -s -o output.html` you should see a lot more information. Please copy and paste this information

**Comment by fanrongqitiancai** [comment]
![image](https://user-images.githubusercontent.com/9015263/152710094-760677b2-cd14-4b7f-b214-bc91ace4528e.png)

I write Python code in eclipse,

import matplotlib. pyplot as plt

plt. figure()

Is right. However, I enter Python in the CMD command window,

Enter the command line and enter

import matplotlib. pyplot as plt

Display:
![image](https://user-images.githubusercontent.com/9015263/152710256-ab09971d-d911-4906-b3eb-794aef3d55e9.png)

**Comment by fanrongqitiancai** [comment]
I modified the environment variable and it can work normally.

**Comment by LaurentRDC** [comment]
Awesome, I'll close this issue for now, but don't hesitate to reopen if it stops working
