### ISSUE TITLE
How can I parse a flowchart using pandoc plot?

### ISSUE THREAD

**Issue by fanrongqitiancai** [LaurentRDC/pandoc-plot#35]
My markdown file is as follows:
```
```plantuml
@startuml
participant John as "John Doe"
participant Jane as "Jane Doe"

John --> Jane: Hello world
@enduml
` ``


```flow
st=>start: Start
e=>end
op=>operation: My Operation
cond=>condition: Yes or No?

st->op->cond
cond(yes)->e
cond(no)->op
```
```

I downloaded plantuml Jar file and pandoc plot Exe in the same folder.
I run command
pandoc --filter pandoc-plot --filter pandoc-katex --css https://cdn.jsdelivr.net/npm/katex@0.13.9/dist/katex.min.css --css style.css --highlight-style pygments  markdown.txt -s   -o output.html

I found that the flowchart was not parsed as a picture.

**Comment by LaurentRDC** [comment]
Hi there. `pandoc-plot` supports the code block classes listed [here](https://github.com/LaurentRDC/pandoc-plot#supported-toolkits). Specifically, I don't know what `flow` refers to.

Is this a type of `plantuml` chart? Usually `plantuml` documents start with `@startuml` and `@enduml@`.

**Comment by fanrongqitiancai** [comment]
My document is written like this 

@startuml
participant John as "John Doe"
participant Jane as "Jane Doe"

John --> Jane: Hello world
@enduml
But pandoc-plotd doesn't work. The output HTML doesn't display the image,

**Comment by LaurentRDC** [comment]
[Can you turn on debug logging just like in this comment?](https://github.com/LaurentRDC/pandoc-plot/issues/34#issuecomment-1030844348)

**Comment by fanrongqitiancai** [comment]
thank you. I solved my problem

**Comment by LaurentRDC** [comment]
Great, don't hesitate to open another issue if you need help
