### ISSUE TITLE
Compatibility with Pandoc 2.17.x?

### ISSUE THREAD

**Issue by mfhepp** [LaurentRDC/pandoc-plot#36]
When installing from conda-forge, I get complicated dependency conflicts, which seem to stem from the fact that pandoc-plot requires a Pandoc version <2.17:

```
Package pandoc conflicts for:
pandoc=2.17.0.1
pandoc-plot=1.4.0 -> pandoc[version='>=2.11,<2.17']
```

Is that a true dependency or something than can be fixed by simply updating the meta-data?

**Comment by LaurentRDC** [comment]
It's an oversight! I will update the metadata

Pandoc has a pretty loose relationship with versioning so I'm erring on the side of caution

**Comment by LaurentRDC** [comment]
[Ok I have merged the changes](https://github.com/conda-forge/pandoc-plot-feedstock/pull/55), it should be possible for you to install pandoc-plot with pandoc 2.17 in ~ 1h maybe?

Thank you for your patience

**Comment by mfhepp** [comment]
Thanks a lot! It seems `conda` does not find the new build, as it bears the same version number (disclaimer: I am by no means a conda expert):

Trying

`conda env create -f mini.yml`

with the following `mini.yml``

```
name: mini
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - pandoc>=2.17
  - pandoc-plot>=1.4.0
```
stops with unsatisfiable conflicts:

```
$ conda env create -f mini.yml

Collecting package metadata (repodata.json): done
Solving environment: / 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                          
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                          

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package pandoc conflicts for:
pandoc-plot[version='>=1.4.0'] -> pandoc[version='>=2.11,<2.17']
pandoc[version='>=2.17']
Note that strict channel priority may have removed packages required for satisfiability.
````

I cleaned all `conda` caches (`conda clean -a`) beforehand.

My guess is that `conda` cannot see that the new build is a higher version and still tries the old one:

https://anaconda.org/conda-forge/pandoc-plot/files?version=1.4.0

shows two 1.4.0 `tar` files:

<img width="976" alt="image" src="https://user-images.githubusercontent.com/671238/155623254-43cea3e5-6dc4-4627-ac80-c255386cd292.png">

Any ideas? And again a huge thanks for your super-swift support!

**Comment by mfhepp** [comment]
Addendum:

`conda search pandoc-plot -c conda-forge` still only finds the old build, as the build tag **`h694c41f_0`** indicates:


```
Loading channels: done
# Name                       Version           Build  Channel             
pandoc-plot                  0.3.0.0               1  conda-forge         
pandoc-plot                  0.4.0.0               0  conda-forge         
pandoc-plot                  0.4.0.1               0  conda-forge         
pandoc-plot                  0.5.0.0               0  conda-forge         
...
pandoc-plot                    1.3.0      h694c41f_0  conda-forge         
pandoc-plot                    1.3.0      h694c41f_1  conda-forge
pandoc-plot                    1.4.0      h694c41f_0 conda-forge
```

**Comment by mfhepp** [comment]
Addendum:

`conda search pandoc-plot -c conda-forge` still only finds the old build, as the build tag **`h694c41f_0`** indicates:


```
Loading channels: done
# Name                       Version           Build  Channel             
pandoc-plot                  0.3.0.0               1  conda-forge         
pandoc-plot                  0.4.0.0               0  conda-forge         
pandoc-plot                  0.4.0.1               0  conda-forge         
pandoc-plot                  0.5.0.0               0  conda-forge         
...
pandoc-plot                    1.3.0      h694c41f_0  conda-forge         
pandoc-plot                    1.3.0      h694c41f_1  conda-forge
pandoc-plot                    1.4.0      h694c41f_0 conda-forge
```

**Comment by mfhepp** [comment]
Addendum:

`conda search pandoc-plot -c conda-forge` still only finds the old build, as the build tag **`h694c41f_0`** indicates:


```
Loading channels: done
# Name                       Version           Build  Channel             
pandoc-plot                  0.3.0.0               1  conda-forge         
pandoc-plot                  0.4.0.0               0  conda-forge         
pandoc-plot                  0.4.0.1               0  conda-forge         
pandoc-plot                  0.5.0.0               0  conda-forge         
...
pandoc-plot                    1.3.0      h694c41f_0  conda-forge         
pandoc-plot                    1.3.0      h694c41f_1  conda-forge
pandoc-plot                    1.4.0      h694c41f_0 conda-forge
```

**Comment by mfhepp** [comment]
Ok, this was just a caching problem in the Conda ecosystem - the fixed build is now found and installed properly.

Again, a big thanks!

**Comment by LaurentRDC** [comment]
Great news! Don't hesitate to raise another issue if you need assistance
