### ISSUE TITLE
Matplotlib code from file will not render if it contains plt.show in a Python comment

### ISSUE THREAD

**Issue by mfhepp** [LaurentRDC/pandoc-plot#41]
pandoc-plot checks if the code for a Matplotlib graph contains `plt.show`{.python}, because `plt.savefig(...){.python} will fail otherwise. This is correct. Unfortunately, it fails to detect if the `plt.show` line will be in a comment, but **only if the source code is imported from a local file.

**Works:**
```{.matplotlib}
import numpy as np
import matplotlib.pyplot as plt
labels = ['A', 'B', 'C']
values = [25, 25, 50]
plt.figure()
plt.pie(values, labels = labels)
# plt.show()
```

```{.matplotlib file="../templates/visualization-templates/pie-matplotlib1.py"}
```

with `pie-matplotlib1.py` like so:

```{.python}
import numpy as np
import matplotlib.pyplot as plt
labels = ['A', 'B', 'C']
values = [25, 25, 50]
plt.figure()
plt.pie(values, labels = labels)
```

**Does not work:**

```{.matplotlib file="../templates/visualization-templates/pie-matplotlib2.py"}
```

with `pie-matplotlib2.py` like so:

```{.python}
import numpy as np
import matplotlib.pyplot as plt
labels = ['A', 'B', 'C']
values = [25, 25, 50]
plt.figure()
plt.pie(values, labels = labels)
# plt.show()
```

**Comment by LaurentRDC** [comment]
Yes, this is a compromise between two things:
1. We don't want plots to silently hang due to `plt.show()`.
2. I don't want the added complexity of parsing Python source to understand whether `plt.show()` is reachable or if it is in a comment, for example.

Is there a reason you want to keep this `# plt.show()` line?

**Comment by mfhepp** [comment]
Thanks for the swift reply - I can live with as it is; maybe one could add a line to the Mathplotlib section in the documentation and issue the error message a bit more prominently. Maybe insert a Para with the error message in case of any error would also be nice - in some workflows, errors from filters are easy to be missed.

**Comment by LaurentRDC** [comment]
Ok I've updated the error message to be more specific. It will be part of the next release. Thanks for your report!
