### ISSUE TITLE
Feature Request: `override: true/false` parameter for default output format in configuration YAML

### ISSUE THREAD

**Issue by mfhepp** [LaurentRDC/pandoc-plot#43]
It would be really cool if you could add an additional keyword parameter like

`override: true`

to the configuration file parser. This would then make it possible to override the output format for all plots in a document by loading a different configuration file (e.g. SVG for Web/HTML, PDF for LaTeX, PNG as a fallback etc.).

Like so ([source](https://laurentrdc.github.io/pandoc-plot/MANUAL.html#cb22-35)):

```
# Default format in which to save the figures. This can be specified 
# individually as well.
format: PNG
# You can instruct pandoc-plot to override the settings in the individual plot attributes with this:
override: true
```

It may make sense to apply it to DPI etc. as well. 

Likely easy to implement, yet very useful!

**Comment by LaurentRDC** [comment]
Hi Martin,

What you're saying is already implemented. From [the manual](https://github.com/LaurentRDC/pandoc-plot/blob/master/MANUAL.md?plain=1#L474):

> A file like the above sets the default values; you can still override them in documents directly.

Consider the example of a configuration file like:

```yaml
format: JPEG
dpi: 100
```

and a document like:

````markdown
# Title

paragraph

```{.python .matplotlib dpi=150 format=PNG}
(...omitted...)
```

```{.python .matplotlib}
(...omitted...)
```

````

The first figure will be a PNG with DPI 150, while the second figure will use the default values of JPEG with DPI of 100

**Comment by mfhepp** [comment]
Thanks! But I mean the opposite: Being able to override parameters from the yaml file in the doc.

My use case is: Graphviz currently has a bug when exporting SVG (rounding errors). Hence, for vector output in Latex, I need to use PDF as a format. But this is ugly in HTML outputs. So I would need to force SVG there.

I could solve this by removing the format directives from the document altogether and just use two sets of yaml config files. But then I would have to force PDF for all plot programs (e.g. also PlantUML) in Latex (doable, but not so nice).

**Comment by LaurentRDC** [comment]
Ahh I see, yes that sounds like the opposite.

Personally, I think that would add too much complexity for the payoff. I like that 'defaults' only go in one direction. 

However, if this is very important to you, I'm happy to review a pull request which implements this change
