### ISSUE TITLE
Full path to executable being ignored

### ISSUE THREAD

**Issue by MageJohn** [LaurentRDC/pandoc-plot#46]
I'm trying to configure the python executable for running matplotlib to one in a virtual environment. I need to do this to have access to all the installed packages there. Unfortunately pandoc-plot seems to ignore the setting and still runs the system version of python.

Specifically I have a source script that looks something like the following, where `some_package` is a package installed only in the venv:

````
```{.matplotlib executable="/full/path/to/venv/bin/python"}
import sys
print(f"sys.executable={sys.executable}", file=sys.stderr)
import some_package
```
````

With this in a markdown file and converting it with pandoc + pandoc-plot, pandoc-plot would give something like following:

```
[pandoc-plot] ERROR | Running command
[pandoc-plot] ERROR |     python  "/tmp/pandocplot4826263390304275862.py"
[pandoc-plot] ERROR | ended with exit code ExitFailure 1
[pandoc-plot] ERROR | *******
[pandoc-plot] ERROR | sys.executable=/usr/bin/python
[pandoc-plot] ERROR | Traceback (most recent call last):
[pandoc-plot] ERROR |   File "/tmp/pandocplot4826263390304275862.py", line 9, in <module>
[pandoc-plot] ERROR |     import some_package
[pandoc-plot] ERROR | ModuleNotFoundError: No module named 'some_package'
[pandoc-plot] ERROR | 
[pandoc-plot] ERROR | *******
[pandoc-plot] ERROR | Command "python  "/tmp/pandocplot4826263390304275862.py"" failed with exit code 1. The script source was: 
[pandoc-plot] ERROR | 
[pandoc-plot] ERROR |  1 > import sys
[pandoc-plot] ERROR |  2 > print(f"sys.executable={sys.executable}", file=sys.stderr)
[pandoc-plot] ERROR |  3 > import some_package
[pandoc-plot] ERROR | 
```

Note that running the venv version of python directly and executing the above script works as expected: it prints the path to the virtual environment's executable (i.e '/full/path/to/venv/bin/python') and correctly imports the package.

I experimented with not setting the executable at all, and noticed that pandoc-plot seems to default to using the `python3` executable. That means that my configuration is being read, but the absolute path is being lost somewhere.

**Comment by LaurentRDC** [comment]
Thank you for your report! Let me take a look

**Comment by LaurentRDC** [comment]
I found the problem, and it is right [here](https://github.com/LaurentRDC/pandoc-plot/blob/master/src/Text/Pandoc/Filter/Plot/Renderers/Matplotlib.hs#L39). In the expression `Executable _ exename`, the directory is ignored (`_`).

I'll try to patch this tonight

**Comment by LaurentRDC** [comment]
In the meantime, you can specify the absolute path to the executable in the `.pandoc-plot.yml` config file like so:

```yaml
#.pandoc-plot.yml in the same directory where you are running `pandoc` and `pandoc-plot`
matplotlib:
  executable: /full/path/to/venv/bin/python
```

**Comment by MageJohn** [comment]
That's strange, it was actually using the configuration file that I first noticed the problem. I didn't mention it earlier because I was trying to provide a minimal description of the issue, and I didn't think the configuration file would make a difference.

I'll try again however, I might have missed something.

**Comment by LaurentRDC** [comment]
You are right, it works now with the config file only because I've fixed [this](https://github.com/LaurentRDC/pandoc-plot/issues/46#issuecomment-1121425208). Stay tuned for the global fix

**Comment by LaurentRDC** [comment]
A fix has been merged into master. I'm preparing a release for tonight

**Comment by MageJohn** [comment]
That's amazing, thank you!

**Comment by LaurentRDC** [comment]
You are most welcome. Don't hesitate to raise other issues if you encounter other problems.
