### ISSUE TITLE
Matplotlib 'tight_bbox' ignored

### ISSUE THREAD

**Issue by MageJohn** [LaurentRDC/pandoc-plot#48]
Hi again,

I've discovered that the `tight_bbox` option for matplotlib is being ignored. What seems to be happening is that in [`Matplotlib.hs`](https://github.com/LaurentRDC/pandoc-plot/blob/f0af92a8b215477cb379d5cc00316b65b6d80114/src/Text/Pandoc/Filter/Plot/Renderers/Matplotlib.hs#L63) the attribute being read is named just `tight`, while the attribute being parsed in [`Renderer.hs`](https://github.com/LaurentRDC/pandoc-plot/blob/f0af92a8b215477cb379d5cc00316b65b6d80114/src/Text/Pandoc/Filter/Plot/Renderers.hs#L123) (and the one documented) is `tight_bbox`. 

This can be reproduced by rendering a matplotlib figure with and without `tight_bbox=true` in the figure attributes; inspecting the generated code shows no difference in the `plt.savefig` call.

Thanks for all your work on this great pandoc filter!

**Comment by LaurentRDC** [comment]
This is a great catch, thanks. I will patch this right away.

**Comment by LaurentRDC** [comment]
This has been fixed in 933daba593196bf3b1ae1f2022d17389552f275c. Releasae 1.5.3 is underway. Cheers
