### ISSUE TITLE
[conda package] Please push to Pandoc 2.18

### ISSUE THREAD

**Issue by mfhepp** [LaurentRDC/pandoc-plot#49]
It would be nice to update pandoc-plot so that it can be used with Pandoc 2.18. Currently, only Pandoc 2.17.x is allowed as per the dependencies, tried with `conda/mamba`:

```
Encountered problems while solving:
  - package pandoc-plot-1.5.3-h694c41f_0 requires pandoc >=2.11,<2.18, but none of the providers can be installed
```

**Comment by LaurentRDC** [comment]
Hi Martin,

Thank you for bringing this to my attention. I've updated the conda-forge recipe. Keep an eye on this [PR for progress](https://github.com/conda-forge/pandoc-plot-feedstock/pull/61).

**Comment by LaurentRDC** [comment]
The recipe has been updated on the conda-forge channel. I don't know how it takes for the change to propagate to users. Let me know if it's still not working by tomorrow.
