### ISSUE TITLE
Graphviz as a Toolkit

### ISSUE THREAD

**Issue by cf020031308** [LaurentRDC/pandoc-plot#5]
Could you please support [Graphviz][graphviz]?

This is also a graph visualization software with which you can plot a graph via a language named DOT.

For Example if you have a file `test.dot` containing the following content:

```dot
digraph {
    A -> B [label="test"];
}
```

Then executing `dot -Tpng -o test.png test.dot` you will get `test.png` generated like this.

![image](https://user-images.githubusercontent.com/5262328/83930843-428e2400-a7cc-11ea-8163-9bbc4f0c71b4.png)

To have more complicated and amazing examples you can visit the official site.

I thought [Graphviz][graphviz] was wildly used and would not be the least popular one among the already supported toolkits.

[graphviz]: <http://graphviz.org/> "Graphviz Official Site"

**Comment by LaurentRDC** [comment]
Yes, I can try to support this toolkit! Let me play around.

**Comment by LaurentRDC** [comment]
@cf020031308 It seems that "Graphviz" is really multiple executables (`dot`, `neato`, `fdp`, ...). 

Are you looking to use `dot` only?

**Comment by cf020031308** [comment]
It doesn't matter whether you use `dot` or `fdp` in the command-line if the value of `layout` is properly set  in DOT file. For example:

```dot
digraph {
    layout=fdp;
    A -> B [label="test"];
}
```

By adding the line `layout=fdp;`, `dot` will generate an image like this:

![image](https://user-images.githubusercontent.com/5262328/83933017-b2ee7280-a7d7-11ea-9daf-d52e04c40e8c.png)

It is exactly the same with what `fdp` gets with the former example.

**Comment by LaurentRDC** [comment]
Ok. What about neato? I'm reading that it has a different use case (i.e. directed graphs vs non-directed graphs).

I'm thinking to have two environments: `graphviz_dot` and `graphviz_neato`. They would differ only by the executable used. What do you think?

**Comment by cf020031308** [comment]
Non-directed graph can be generated like this:

```dot
graph {
    A -- B [label="test"];
}
```

It starts with 'graph' instead of 'digraph' (I think 'digraph' stands for 'directed graph'). Then no arrows (->) are allowed in the script.

And this is the output of `dot`:

![image](https://user-images.githubusercontent.com/5262328/83945658-be28b900-a83e-11ea-940d-a1a57fd86cf9.png)

So indeed I use `dot` only.

**Comment by LaurentRDC** [comment]
Ok tests are passing, so graphviz will be available in the next release of pandoc-plot (0.6.0.0). I will try to make a release today!

**Comment by LaurentRDC** [comment]
pandoc-plot 0.6.0.0 has been released, including support for Graphviz.

Please try it and let me know if it works as you expected.

For your example above:

````markdown
# Document

```{.graphviz caption="Example graph"}
digraph {
    A -> B [label="test"];
}
```

````

**Comment by cf020031308** [comment]
Yes, it works!

One more thing, the script language that graphviz use is called DOT, so some editors/IDEs can recognize it and highlight the code if the code block starts with `'''dot`.

E.g. on Github, this code block will be highlighted:

    ```dot
    digraph {
      A -> B;
    }
    ```

```dot
digraph {
  A -> B;
}
```

But if the code block starts with `'''graphviz`,

    ```graphviz
    digraph {
      A -> B;
    }
    ```

it would be plain:

```graphviz
digraph {
  A -> B;
}
```

So it is practical to write the code block in document marked with `dot` but `graphviz`. Thus I suggest to trigger this filter by `dot` or either, instead of only `graphviz`

**Comment by LaurentRDC** [comment]
@cf020031308 I don't want to re-use language names as filters because some people might want to have code blocks and plots. As described in the README [here](https://github.com/LaurentRDC/pandoc-plot#code-highlighting), you can activate code highlighting in Markdown like so:

````markdown
```{.dot .graphviz}
digraph {
  A -> B;
}
```
````

**Comment by cf020031308** [comment]
@LaurentRDC you are right. Then I think it's done. I embed graphviz/gnuplot directly in markdown files in order to simplify the management of those code snippets. This filter can save me lots of efforts when converting them to docx. Thank you!

**Comment by LaurentRDC** [comment]
It was my pleasure :)
