### ISSUE TITLE
Support Penrose diagrams

### ISSUE THREAD

**Issue by mgajda** [LaurentRDC/pandoc-plot#54]
Penrose is a diagramming tool for maths handbooks: https://github.com/penrose/penrose
It uses declarative mathematical notation.

**Comment by LaurentRDC** [comment]
Hello,

I'm not familiar with penrose. In order to add a penrose backend, would you be able to provide me with:
1. An example script;
2. A shell script which would export a diagram into either an image file, or an HTML + JS page?

**Comment by mgajda** [comment]
Since authors of Penrose no longer seem to support building it on own machine, nor running anywhere but in a browser, I close this ticket as unpracticable.
