### ISSUE TITLE
Unable to install with conda on linux

### ISSUE THREAD

**Issue by frcl** [LaurentRDC/pandoc-plot#6]
There seems to be no linux package on conda-forge. Would it be possible to add those?

On an unrelated issue: The tarball with the linux binary on the realeases page has filename that end with .xz but it is actually compressed with gzip (.gz). This is because in [this line](https://github.com/LaurentRDC/pandoc-plot/blob/5353c6afce65ce5a2899d138ed953bcd0be8c7ea/.azure/azure-linux-template.yml#L53) the -z option is used (-J would be xz). This is not a big issue, but software that only looks at the file extension can fail because of this.

By the way this is a very nice tool. I like it a lot.

**Comment by LaurentRDC** [comment]
Hello,

Regarding the linux package on conda-forge, I have been [trying to get one working](https://github.com/conda-forge/pandoc-plot-feedstock/pull/10) for a while. Unfortunately, I don't understand how to fix this error. Maybe you can help me figure it out?

As for the extension, thank you :) I will fix it right away.

**Comment by frcl** [comment]
Sure, I can take a look at it.

**Comment by LaurentRDC** [comment]
Hey there,

So, the ability to install pandoc-plot on linux via conda is limited by the conda-forge build environment, which is based on CentOS 6. There are no recent Haskell compilers that are supported on CentOS 6, only on CentOS 7. See [here](https://github.com/conda-forge/pandoc-plot-feedstock/pull/10#issuecomment-663916240) for a discussion.

Apparently, conda-forge is moving on to [CentOS 7 soon](https://github.com/conda-forge/pandoc-plot-feedstock/pull/10#issuecomment-663918967). Until then, pandoc-plot won't be installable via conda-forge on linux.

Linked issue: https://github.com/conda-forge/pandoc-plot-feedstock/pull/20

**Comment by frcl** [comment]
No need to be sorry. I'm glad that progress was made.

**Comment by LaurentRDC** [comment]
[I have added statically-linked Linux binaries to the conda-forge feedstock](https://github.com/conda-forge/pandoc-plot-feedstock/pull/24). It should be available to install in a few hours.

Please let me know if it works correctly on your machine!

**Comment by frcl** [comment]
It works well, thank you very much :)
