### ISSUE TITLE
Half-width or text-wrapped figures?

### ISSUE THREAD

**Issue by mgajda** [LaurentRDC/pandoc-plot#65]
It would be nice to add an option to select the environment that changes the figures into half-width or text-wrapped.

Now it may be only achieved by using a generic re-definition of environment, as far as I know.

**Comment by mgajda** [comment]
A similar option for figure-less inline images would be useful.

Either of these just change headers/trailers in either LaTeX or HTML.

**Comment by mgajda** [comment]
For half-width figures, we may use the following:
```latex
\begin{minipage}{\columnwidth}
\includegraphics[width=\linewidth,height=0.28\textheight]{...}
\caption{ ... }
\label{...}
\end{minipage}
```

**Comment by LaurentRDC** [comment]
`pandoc-plot` strictly generates a Pandoc Image block; the modification of this image block should be the domain of another Pandoc filter.

**Comment by mgajda** [comment]
The problem with `pandoc` image block is that it needs to be generated differently for a wrapped figure, and for half-width figure.
