### ISSUE TITLE
Missing file for `--manual`

### ISSUE THREAD

**Issue by mgajda** [LaurentRDC/pandoc-plot#69]
Installing `pandoc-plot` with `stack install` or `cabal install` will not install the `manual.html` file in the location where `pandoc-plot` currently expects it.

So installed `pandoc-plot` manual may fail to work when it tries to open file in current directory, instead of installation `share/` directory.

**Comment by LaurentRDC** [comment]
Is this an issue you have actually encountered?

`manual.html` is [stored in the executable using Template Haskell](https://github.com/LaurentRDC/pandoc-plot/blob/08994b92a0a3e6dcb2a2135cc62879dc7a566bce/executable/ManPage.hs#L29); it does not need to be on the system where pandoc-plot is installed. `manual.html` is also [part of the source](https://github.com/LaurentRDC/pandoc-plot/blob/08994b92a0a3e6dcb2a2135cc62879dc7a566bce/pandoc-plot.cabal#L29) as expected.
